---
galaxy_info:
  author: Participation Infrastructure
  description:
  company: Mozilla
  license: license MPL
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - jessie
  categories:
  - cloud
  - system
  - web
dependencies: []
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.

