---
- hosts: multi
  tasks:
  - name: Add mesosphere deb repository keys
    sudo: yes
    apt_key: keyserver=keyserver.ubuntu.com id=E56151BF

  - name: Install mesosphere deb repository
    sudo: yes
    apt_repository: repo="deb http://repos.mesosphere.io/ubuntu trusty main" state=present

  - name: Update repository cache
    sudo: yes
    apt: update_cache=yes cache_valid_time=3600

- hosts: master
  tasks:
  - name: Install mesosphere
    sudo: yes
    apt: name=mesosphere state=present

- hosts: slave
  tasks:
  - name: Install mesos
    sudo: yes
    apt: name=mesos state=present

- hosts: multi
  tasks:
  - name: Setup zookeeper connection info for Mesos
    sudo: yes
    template:
      src: "templates/zk"
      dest: "/etc/mesos/zk"
      owner: root
      group: root
      mode: 0644

- hosts: master
  tasks:
    - name: Setup zookeeper master servers configuration
      sudo: yes
      template:
        src: "templates/zk.id"
        dest: "/etc/zookeeper/conf/myid"
        owner: root
        group: root
        mode: 0644
      template:
        src: "templates/zoo.cfg"
        dest: "/etc/zookeeper/conf/zoo.cfg"
        owner: root
        group: root
        mode: 0644
    - name: Setup quorum for mesos-master
      sudo: yes
      template:
        src: "templates/quorum"
        dest: "/etc/mesos-master/quorum"
        owner: root
        group: root
        mode: 0644
    - name: Setup ip for mesos-master
      sudo: yes
      template:
        src: "templates/ip"
        dest: "/etc/mesos-master/ip"
        owner: root
        group: root
        mode: 0644
    - name: Setup hostname for mesos-master
      sudo: yes
      template:
        src: "templates/ip"
        dest: "/etc/mesos-master/ip"
        owner: root
        group: root
        mode: 0644
    - name: Create directory for marathon configuration
      sudo: yes
      file:
        path: /etc/marathon/conf
        state: directory
    - name: Copy mesos-master hostnames to marathon configuration
      sudo: yes
      command: cp /etc/mesos-master/hostname /etc/marathon/conf/
    - name: Setup zookeeper configuration on marathon configuration
      sudo: yes
      template:
        src: "templates/marathon"
        dest: "/etc/marathon/conf/zk"
        owner: root
        group: root
        mode: 0644

