---
# file: slave.yml
- name: Install mesos
  apt: name=mesos state=present

- name: Stop and disable zookeeper in slave nodes
  service:
    name: zookeeper
    enabled: false
    state: stopped

- name: Stop and disable mesos-master in slave nodes
  service:
    name: mesos-master
    enabled: false
    state: stopped

- name: Setup ip for mesos-slave
  template:
    src: "templates/hostname"
    dest: "/etc/mesos-slave/ip"
    owner: root
    group: root
    mode: 0644

- name: Setup hostname for mesos-slave
  template:
    src: "templates/hostname"
    dest: "/etc/mesos-slave/hostname"
    owner: root
    group: root
    mode: 0644
  notify: restart mesos-slave
